Minor improvements
AmazingCodingSkills/Converter pull request #27
Opened 2023-02-14 15:32 UTC by KSVdvlpr

2023-02-15 13:34 UTC, MrKovalev approved these changes

2023-02-15 17:24 UTC, MrKovalev requested changes
Вообще, красавчик 👍  Много успел за день. Не напрягайся из-за кучи комментариев. Я просто посмотрел с большей степенью доеба чем делал это раньше. Можешь по комментариям внести правки сюда отдельными коммитами. Если вопросики есть - отвечай мне на мои комментарии

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/base/CurrencyRatesRepository.kt
> +const val MESSAGE_EXCEPTION_FOR_CALCULATOR = "Введите число, которое не начиначется с  '.'"
Хардкод. Локализация на другие языки сломается. Нужно унести это сообщение в ресурсы и использовать оттуда. Например, из презентера ты можешь передавать **R.string.id** твоей строки, а уже на фрагменте делать **context.getString(id)** и достать значение из ресурсов. Тогда у тебя будет работать поддержка разных языков

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/base/CustomDialog.kt
>  class CustomDialog: DialogFragment() {
Давай так и назовем `NetworkAvailabilityDialogFragment`?

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/base/CustomDialog.kt
> +        val height = (resources.displayMetrics.heightPixels * 0.40).toInt()
Вот эту черную магию можно не делать. Оно сейчас никак не влияет на отображение.
Достаточно будет `dialog?.window?.setLayout(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT)` и выглядеть будет также. Сработает так потому что у тебя в верстке итак уже указаны размеры и отступы

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/base/CustomDialog.kt
> +        dialog!!.window?.setLayout(width, ViewGroup.LayoutParams.WRAP_CONTENT)
от `!!` я бы избавлялся в сторону safe call через `?`

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/base/NetworkRepository.kt
>      fun isCheckStatusInternet() : Boolean {
Тогда давай назовем `isInternerUnavailable`?

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/features/calculator/presenter/CalculatorPresenter.kt
> +            if (input == "0." || input == "0") {
Ну пока пойдет, только мы по-прежнему можем ввести 00. и все сломается, например. Но пока я бы предложил оставить так и:
- вынести этот кусочек в отдельную функцию `isInputValid()`в котором ты делаешь все проверки введенного инпута и переиспользовать его в `onTextInputChangedOne` и `onTextInputChangedTwo` -> уберем дублирование
- сейчас ты все равно при вводе невалидного инпута посылаешь запрос к серверу на конвертацию, можешь чекнуть в логах. Лишняя работа. Нужно вызывать onCurrencyConverted() только тогда, когда мы уверены что инпут валиден ->  После изменения выше этой проблемы не должно быть

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/features/calculator/presenter/CalculatorPresenter.kt
> +        onDialogWarning()
Ты чекнешь наличие интернета и мб покажешь даже диалог, но все равно попытаешься ниже вызвать запрос, заведомо зная что он не сможет выполнится и будет ошибка сети. Поэтому нужно вызывать репозиторий только когда есть интернет

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/features/rate/presenter/RatesPresenter.kt
> +        view?.hideProgress()
А если интернет вдруг станет медленнее и `onSavedCurrencyGated()` будет выполняться дольше обычного? Тогда состояние загрузки не будет отражать то что ты реально что-то сейчас загружаешь, т.к ты сразу после вызова загрузки остановил крутилку. Нужно завершать показ загрузки только в том случае когда мы реально уже загрузили данные, либо когда свалились с ошибкой

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/res/layout/dialog_custom.xml
> +            android:layout_height="30dp"
По материал гайдлайнам лучше брать с шагом в 4. Т.е 4-8-12-16 и т.д

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/res/layout/dialog_custom.xml
>          android:layout_height="140dp"
А вот это хак. Лучше стараться избегать таких жесткий указаний размеров. Конкретно в этом случае верстка всего диалога сделана чуток криво. Если покрутить этот диалог на разных девайсах и в разных положениях, с разным текстом у диалога и т.д, то все поедет криво

Накидаю тогда тезисно, попробуй почекать? Не могу над каждой строчкой оставить комменты:
- Зачем дополнительный ConstraintLayout внутри уже существующего рутового ConstraintLayout? Получается излишняя вложенность и сложнее рендерить такой UI. Констрейнт как-раз придумали для того чтобы сделать ее поменьше. Тут можно обойтись только одним ConstraintLayout
- Везде хардкоды размеров вьюх. Например, ширина 140dp и т.д. Нужно стараться верстать так чтобы все было завязано на констрейнты. Т.е правильно выставлять привязки куда и какие вью ты завязываешь. А самим вью делать либо wrap_content(по размеру контента внутри вью), либо 0dp(т.е полностью подчиняться заданным якорям и делать размер под них) либо match_parent и вообще растягивать на всю
- android:background="@color/white" хардкод, сломается темная тема. Нужно использовать атрибут из темы. Тоже самое касается цвета текста, например
- лишние атрибуты вроде layout_gravity, они не работают с констрейнтом. Это скорее в линеаре или релатив лейауте

2023-02-15 17:24 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/features/calculator/presenter/CalculatorPresenter.kt
> +        try {
Не совсем понял зачем тут try/catch. Как будто никакой ошибки возникать не должно. Ты просто должен правильно валидировать ввод пользователя. Тут в пуле писал про это.

Если это кейс когда ты вводишь 0. и у тебя пытается преобразовать это в Double и возникает ошибка, то try/catch тут скорее исправляет следствие, а не причину. Уже произошла ошибка, слишком поздно. Нужно не позволять вызывать преобразование если мы хуйню написали просто. После того как ты сделаешь валидацию - проблема уйдет

2023-02-16 06:18 UTC, KSVdvlpr commented on app/src/main/java/com/currency/converter/base/CustomDialog.kt
> +        dialog!!.window?.setLayout(width, ViewGroup.LayoutParams.WRAP_CONTENT)
В верхнем примере dialog?.window?.setLayout(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT) уже лишен !!, коммит отдельный заливать не буду.

2023-02-16 10:58 UTC, KSVdvlpr commented on app/src/main/java/com/currency/converter/features/rate/presenter/RatesPresenter.kt
> +        view?.hideProgress()
Вот тут не совсем понимаю как переделать. Понимаю, что скорее всего, мне нужно посмотреть как-то на то, завершился метод или нет. А я просто запускаю метод и все.

2023-02-16 10:58 UTC, KSVdvlpr commented on app/src/main/java/com/currency/converter/features/rate/presenter/RatesPresenter.kt
> +        view?.hideProgress()
Я постарался выставить флаги true false, но думаю, что это бесполезно.

2023-02-16 12:33 UTC, KSVdvlpr commented on app/src/main/java/com/currency/converter/features/calculator/presenter/CalculatorPresenter.kt
> +        try {
Мишань, а вот тут когда начинаешь вводить с "." numberFormatException. Поэтому добавил try catch. Попробовал убрать и провалидировать, не очень получилось у меня, может я конечно криво сделал, но решил пока оставить так.

2023-02-16 12:47 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/features/calculator/presenter/CalculatorPresenter.kt
> +        try {
Немного по-другому имел ввиду. Обсудим сегодня

2023-02-16 12:49 UTC, MrKovalev commented on app/src/main/java/com/currency/converter/features/rate/presenter/RatesPresenter.kt
> +        view?.hideProgress()
Ага. Надо по-другому. Обсудим сегодня

2023-02-16 12:51 UTC, KSVdvlpr commented on app/src/main/java/com/currency/converter/features/calculator/presenter/CalculatorPresenter.kt
> +        try {
ок

2023-02-16 12:51 UTC, KSVdvlpr commented on app/src/main/java/com/currency/converter/features/rate/presenter/RatesPresenter.kt
> +        view?.hideProgress()
ок

2023-02-16 14:16 UTC, MrKovalev approved these changes

2023-02-16 14:48 UTC, merged